FCMQT = FCMQT or {}
-- Defaults Vars
-- Version : 0.95.b15
FCMQT.defaults = {	["position"] = { ["point"]=TOPLEFT, ["relativePoint"]=TOPLEFT, ["offsetX"]=1000, ["offsetY"]=300 },
					["Language"] = "English",
					["Preset"] = "Custom",
					["BgAlpha"] = 70,
					["BgWidth"] = 275,
					["BgOption"] = true,
					["BgColor"] = { ["r"]=0.062745, ["g"]=0.113725, ["b"]=0.152941, ["a"]=0.155738 },
					["PositionLockOption"] = false,
					["ShowJournalInfosOption"] = true,
					["ShowJournalInfosFont"] = "Skyrim Handwritten",
					["ShowJournalInfosSize"] = 14,
					["ShowJournalInfosStyle"] = "soft-shadow-thin",
					["ShowJournalInfosColor"] = { ["r"] = 0.800000, ["g"] = 0.670588, ["b"] = 0.219608, ["a"] = 1 },
					["DirectionBox"] = "BOTTOM",
					["TitleSize"] = 17,
					["TitlePadding"] = 5,
					["TitleFont"] = "Univers 67",
					["TitleStyle"] = "shadow",
					["TitleColor"] = { ["r"]=0.800000, ["g"]=0.513726, ["b"]=0.196078, ["a"]=1 },
					["TextSize"] = 14,
					["TextPadding"] = 24,
					["TextFont"] = "Univers 57",
					["TextStyle"] = "soft-shadow-thin",
					["QuestsHideObjOptional"] = false,
					["TextColor"] = { ["r"]=1, ["g"]=1, ["b"]=1, ["a"]=0.950820 },
					["TextCompleteColor"] = { ["r"]=0.603922, ["g"]=0.603922, ["b"]=0.603922, ["a"]=0.950820 },
					["TextOptionalColor"] = { ["r"]=0.945098, ["g"]=1, ["b"]=0.796078, ["a"]=0.950820 },
					["TextOptionalCompleteColor"] = { ["r"]=0.603922, ["g"]=0.603922, ["b"]=0.603922, ["a"]=0.950820 },
					["ClueColor"] = { ["b"] = 0.603922, ["r"] = 0.603922, ["g"] = 0.603922, ["a"] = 0.950820 },
					["SortOrder"] = "Zone+Name",
					["NbQuests"] = 12,
					["AutoShare"] = false,
					["AutoAcceptSharedQuests"] = false,
					["AutoRefuseSharedQuests"] = false,
					["QuestIconOption"] = true,
					["QuestIcon"] = "Arrow ESO (Default)",
					["QuestIconSize"] = 22,
					["QuestIconColor"] = { ["r"]=1, ["g"]=1, ["b"]=1, ["a"]=1 },
					["QuestsAreaOption"] = true,
					["QuestsHybridOption"] = true,
					["QuestsAreaSize"] = 21,
					["QuestsAreaFont"] = "Skyrim Handwritten",
					["QuestsAreaStyle"] = "shadow",
					["QuestsAreaPadding"] = 5,
					["QuestsAreaColor"] = { ["r"] = 0.800000, ["g"] = 0.670588, ["b"] = 0.219608, ["a"] = 1 },
					["QuestsShowTimerOption"] = true,
					["QuestHideObjOption"] = false,
					["QuestsLevelOption"] = true,
					["QuestsHideZoneOption"] = false,
					["QuestsZoneOption"] = false,
					["QuestsZoneGuildOption"] = true,
					["QuestsZoneMainOption"] = true,
					["QuestsZoneCyrodiilOption"] = true,
					["QuestsZoneClassOption"] = true,
					["QuestsZoneCraftingOption"] = true,
					["QuestsZoneGroupOption"] = true,
					["QuestsZoneDungeonOption"] = true,
					["QuestsZoneRaidOption"] = true,
					["QuestsZoneAVAOption"] = true,
					["QuestsZoneEventOption"] = true,
					["QuestsZoneBGOption"] = true,
					["QuestsOptionalOption"] = false,
					["QuestsUntrackHiddenOption"] = false,
					["QuestsNoFocusOption"] = false,
					["GetFocusedQuestAreaNoTrans"] = false,
					["QuestsNoFocusTransparency"] = 55,
					["Button1"] = "Change Assisted Quest",
					["Button2"] = "Share a Quest",
					["Button3"] = "Filter by Current Zone",
					["Button4"] = "Show on Map",
					["Button5"] = "Remove a Quest",
					["BufferRefreshTime"] = "10",
					["QuestsFilter"] = {},
}

FCMQT.PresetDefaults = {
					["BgAlpha"] = 70,
					["BgWidth"] = 275,
					["BgOption"] = true,
					["BgColor"] = { ["r"]=0.062745, ["g"]=0.113725, ["b"]=0.152941, ["a"]=0.155738 },
					["PositionLockOption"] = false,
					["ShowJournalInfosOption"] = true,
					["ShowJournalInfosFont"] = "Skyrim Handwritten",
					["ShowJournalInfosSize"] = 14,
					["ShowJournalInfosStyle"] = "soft-shadow-thin",
					["ShowJournalInfosColor"] = { ["r"] = 0.800000, ["g"] = 0.670588, ["b"] = 0.219608, ["a"] = 1 },
					["DirectionBox"] = "BOTTOM",
					["TitleSize"] = 17,
					["TitlePadding"] = 5,
					["TitleFont"] = "Univers 67",
					["TitleStyle"] = "shadow",
					["TitleColor"] = { ["r"]=0.800000, ["g"]=0.513726, ["b"]=0.196078, ["a"]=1 },
					["TextSize"] = 14,
					["TextPadding"] = 24,
					["TextFont"] = "Univers 57",
					["TextStyle"] = "soft-shadow-thin",
					["QuestsHideObjOptional"] = false,
					["TextColor"] = { ["r"]=1, ["g"]=1, ["b"]=1, ["a"]=0.950820 },
					["TextCompleteColor"] = { ["r"]=0.603922, ["g"]=0.603922, ["b"]=0.603922, ["a"]=0.950820 },
					["TextOptionalColor"] = { ["r"]=0.945098, ["g"]=1, ["b"]=0.796078, ["a"]=0.950820 },
					["TextOptionalCompleteColor"] = { ["r"]=0.603922, ["g"]=0.603922, ["b"]=0.603922, ["a"]=0.950820 },
					["ClueColor"] = { ["b"] = 0.603922, ["r"] = 0.603922, ["g"] = 0.603922, ["a"] = 0.950820 },
					["SortOrder"] = "Zone+Name",
					["NbQuests"] = 12,
					["AutoShare"] = false,
					["AutoAcceptSharedQuests"] = false,
					["AutoRefuseSharedQuests"] = false,
					["QuestIconOption"] = true,
					["QuestIcon"] = "Arrow ESO (Default)",
					["QuestIconSize"] = 22,
					["QuestIconColor"] = { ["r"]=1, ["g"]=1, ["b"]=1, ["a"]=1 },
					["QuestsAreaOption"] = true,
					["QuestsHybridOption"] = true,
					["QuestsAreaSize"] = 21,
					["QuestsAreaFont"] = "Skyrim Handwritten",
					["QuestsAreaStyle"] = "shadow",
					["QuestsAreaPadding"] = 5,
					["QuestsAreaColor"] = { ["r"] = 0.800000, ["g"] = 0.670588, ["b"] = 0.219608, ["a"] = 1 },
					["QuestsShowTimerOption"] = true,
					["QuestHideObjOption"] = false,
					["QuestsLevelOption"] = true,
					["QuestsHideZoneOption"] = false,
					["QuestsZoneOption"] = false,
					["QuestsZoneGuildOption"] = true,
					["QuestsZoneMainOption"] = true,
					["QuestsZoneCyrodiilOption"] = true,
					["QuestsZoneClassOption"] = true,
					["QuestsZoneCraftingOption"] = true,
					["QuestsZoneGroupOption"] = true,
					["QuestsZoneDungeonOption"] = true,
					["QuestsZoneRaidOption"] = true,
					["QuestsZoneAVAOption"] = true,
					["QuestsZoneEventOption"] = true,
					["QuestsZoneBGOption"] = true,
					["QuestsOptionalOption"] = false,
					["QuestsUntrackHiddenOption"] = false,
					["QuestsNoFocusOption"] = false,
					["GetFocusedQuestAreaNoTrans"] = false,
					["QuestsNoFocusTransparency"] = 55,
					["Button1"] = "Change Assisted Quest",
					["Button2"] = "Share a Quest",
					["Button3"] = "Filter by Current Zone",
					["Button4"] = "Show on Map",
					["Button5"] = "Remove a Quest"
}

FCMQT.preset1 = {
					["BgAlpha"] = 100,
					["BgWidth"] = 201,
					["BgOption"] = true,
					["BgColor"] = { ["b"] = 0.152941, ["r"] = 0.062745, ["g"] = 0.113725, ["a"] = 0.155738},
					["ShowJournalInfosOption"] = true,
					["ShowJournalInfosFont"] = "Skyrim Handwritten",
					["ShowJournalInfosSize"] = 14,
					["ShowJournalInfosStyle"] = "soft-shadow-thin",
					["ShowJournalInfosColor"] = { ["r"] = 0.800000, ["g"] = 0.670588, ["b"] = 0.219608, ["a"] = 1 },
					["TitleSize"] = 13,
					["TitlePadding"] = 8,
					["TitleFont"] = "Trajan Pro",
					["TitleStyle"] = "soft-shadow-thick",
					["TitleColor"] = { ["b"] = 1, ["r"] = 1, ["g"] = 1, ["a"] = 1 },				
					["TextSize"] = 12,
					["TextPadding"] = 24,
					["TextFont"] = "Futura Condensed",
					["TextStyle"] = "soft-shadow-thin",
					["QuestsHideObjOptional"] = false,
					["TextColor"] = { ["b"] = 1, ["r"] = 1, ["g"] = 1, ["a"] = 0.950820 },
					["TextCompleteColor"] = { ["b"] = 0.603922, ["r"] = 0.603922, ["g"] = 0.603922, ["a"] = 0.950820 },
					["TextOptionalColor"] = { ["b"] = 0.796078, ["r"] = 0.945098, ["g"] = 1, ["a"] = 0.950820},
					["TextOptionalCompleteColor"] = { ["b"] = 0.603922, ["r"] = 0.603922, ["g"] = 0.603922, ["a"] = 0.950820 },
					["ClueColor"] = { ["b"] = 0.603922, ["r"] = 0.603922, ["g"] = 0.603922, ["a"] = 0.950820 },
					["SortOrder"] = "Zone+Name",
					["NbQuests"] = 12,
					["AutoShare"] = false,					
					["AutoAcceptSharedQuests"] = false,
					["AutoRefuseSharedQuests"] = false,
					["QuestIconOption"] = true,
					["QuestIcon"] = "Arrow ESO (Default)",
					["QuestIconSize"] = 22,
					["QuestIconColor"] = { ["b"] = 1, ["r"] = 1, ["g"] = 1, ["a"] = 1 },
					["QuestsAreaOption"] = true,
					["QuestsHybridOption"] = true,
					["QuestsAreaFont"] = "Trajan Pro",
					["QuestsAreaStyle"] = "thick-outline",
					["QuestsAreaPadding"] = 4,
					["QuestsAreaSize"] = 16,
					["QuestsAreaColor"] = { ["b"] = 0.360784, ["r"] = 0.909804, ["g"] = 0.792157, ["a"] = 1 },					
					["QuestsShowTimerOption"] = true,
					["QuestHideObjOption"] = false,
					["QuestsLevelOption"] = true,					
					["QuestsZoneOption"] = false,
					["QuestsZoneGuildOption"] = true,
					["QuestsZoneMainOption"] = true,
					["QuestsZoneCyrodiilOption"] = true,
					["QuestsZoneClassOption"] = true,
					["QuestsZoneCraftingOption"] = true,
					["QuestsZoneGroupOption"] = true,
					["QuestsZoneDungeonOption"] = true,
					["QuestsZoneRaidOption"] = true,
					["QuestsZoneAVAOption"] = true,
					["QuestsZoneEventOption"] = true,
					["QuestsZoneBGOption"] = true,
					["QuestsOptionalOption"] = false,
					["QuestsUntrackHiddenOption"] = true,
					["QuestsNoFocusOption"] = true,
					["GetFocusedQuestAreaNoTrans"] = false,
					["QuestsNoFocusTransparency"] = 60,
					["Button1"] = "Change Assisted Quest",
					["Button2"] = "Share a Quest",
					["Button3"] = "Filter by Current Zone",
					["Button4"] = "Show on Map",
					["Button5"] = "Remove a Quest"
}